### ISSUE TITLE
Support Swift 2.0

### ISSUE THREAD

**Issue by mcudich** [joshaber/SwiftBox#14]
There are a few issues with compiling SwiftBox in Xcode 7 (mostly around Printable and DebugPrintable no longer being around). Would it be possible to add a Swift 2.0-compatible branch? Thanks!

**Comment by joshaber** [comment]
Absolutely. Pull requests welcome :smile:

**Comment by mcudich** [comment]
Sent!

**Comment by joshaber** [comment]
See https://github.com/joshaber/SwiftBox/tree/swift-2.0. :boom:
